apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-runtime
  namespace: llm-serving
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: vLLM CUDA - Qwen3.6-35B-A3B-AWQ
  labels:
    opendatahub.io/dashboard: "true"
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - name: kserve-container
      image: docker.io/vllm/vllm-openai:latest
      command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
      args:
        - --port=8080
        - --model=cyankiwi/Qwen3.6-35B-A3B-AWQ-4bit
        - --served-model-name={{.Name}}
        - --max-model-len=40960
        - --dtype=auto
        - --gpu-memory-utilization=0.95
        - --max-num-seqs=16
        - --trust-remote-code
        - --reasoning-parser=qwen3
        - --enable-auto-tool-choice
        - --tool-call-parser=qwen3_coder
        - --enable-prefix-caching
      env:
        - name: HF_HOME
          value: /opt/models
        - name: HF_HUB_OFFLINE
          value: "0"
        - name: TRANSFORMERS_OFFLINE
          value: "0"
        - name: HOME
          value: /opt/models
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
